import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0e1524',
    paddingTop: Platform.OS === 'ios' ? 54 : 32, // + espace pour la Dynamic Island
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  center: {
    flex: 1,
    backgroundColor: '#0e1524',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    color: '#fff',
    fontSize: 30,
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 8,
    letterSpacing: 1.6,
    textAlign: 'center',
    textShadowColor: '#181c36',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
  },
  subtitle: {
    color: '#bbc2df',
    fontSize: 18,
    marginBottom: 32,
    textAlign: 'center',
    fontStyle: 'italic',
    letterSpacing: 0.16,
  },
  tripCard: {
    backgroundColor: '#1a2335',
    borderRadius: 20,
    padding: 20,
    marginVertical: 20,
    shadowColor: '#132040',
    shadowOpacity: 0.21,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 7,
    borderWidth: 1.5,
    borderColor: '#232c4a',
  },
  tripTitle: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 22,
    marginBottom: 4,
    letterSpacing: 0.65,
    textShadowColor: '#181c36',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  tripSub: {
    color: '#c2cee9',
    marginBottom: 16,
    fontSize: 17,
    letterSpacing: 0.1,
  },
  sectionTitle: {
    fontWeight: 'bold',
    color: '#47afff',
    marginTop: 20,
    marginBottom: 12,
    fontSize: 19,
    letterSpacing: 1,
    textShadowColor: '#12233f77',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  itemBox: {
    backgroundColor: '#232f45',
    borderRadius: 15,
    padding: 18,
    marginBottom: 21,
    shadowColor: '#0d0f1a',
    shadowOpacity: 0.14,
    shadowOffset: { width: 1, height: 3 },
    shadowRadius: 7,
    elevation: 4,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    borderBottomWidth: 0.7,
    borderBottomColor: '#314060',
    paddingBottom: 9,
  },
  itemName: {
    color: '#f7f9fa',
    flex: 2,
    fontSize: 18,
    fontWeight: '500',
    letterSpacing: 0.22,
  },
  itemQty: {
    color: '#47afff',
    flex: 1,
    textAlign: 'center',
    fontSize: 16.5,
    fontWeight: '700',
    letterSpacing: 0.23,
  },
  input: {
    backgroundColor: '#182135',
    color: '#fff',
    borderRadius: 10,
    padding: 9,
    width: 84,
    marginLeft: 12,
    borderWidth: 1.5,
    borderColor: '#273a5a',
    fontSize: 17,
    textAlign: 'right',
    shadowColor: '#000',
    shadowOpacity: 0.09,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 2,
  },
  total: {
    color: '#2ef48c',
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 24,
    marginTop: 8,
    textAlign: 'right',
    letterSpacing: 0.8,
    backgroundColor: '#1b2937',
    paddingVertical: 11,
    borderRadius: 13,
    paddingHorizontal: 20,
    shadowColor: '#0c2426',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
  },
  button: {
    paddingVertical: 16,
    borderRadius: 15,
    marginVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2b3a5c',
    borderWidth: 1,
    borderColor: '#2b3a5c',
    shadowColor: '#191e2e',
    shadowOpacity: 0.17,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 7,
    elevation: 2,
  },
  buttonPrimary: {
    backgroundColor: '#348afd',
  },
  buttonSecondary: {
    backgroundColor: '#242f48',
    borderWidth: 1.6,
    borderColor: '#348afd',
  },
  buttonDanger: {
    backgroundColor: '#e74c3c',
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  buttonTextSecondary: {
    color: '#348afd',
    fontWeight: 'bold',
    fontSize: 18,
    textTransform: 'uppercase',
  },
  buttonSpacing: {
    marginBottom: 19,
    marginTop: 8,
  },
  noTrip: {
    color: '#fff',
    marginTop: 38,
    textAlign: 'center',
    fontSize: 18,
    opacity: 0.85,
  },
  buttonRight: {
  alignItems: 'flex-end',
  width: '100%',
},
});

export default styles;